title: Danty Cook Portfolio
description: Data Analytics & Data Engineering Projects

url: "https://dantydcook.github.io"
baseurl: "/portfolio"

permalink: pretty

markdown: kramdown
theme: minima

collections:
  pages:
    output: true
    permalink: /:path/

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-analytics

analytics:
  provider: google-gtag
  gtag:
    tracking_id: G-51LKT0PS78
