title: Danty Cook Portfolio
description: Data Analytics & Data Engineering Projects

#url: "https://dantydcook.github.io"
#baseurl: "/portfolio"

url: "https://www.dantydcook.com"
baseurl: ""

# Optional socials (used conditionally)
linkedin: "https://www.linkedin.com/in/your-profile-slug"
github: "https://github.com/dantydcook"  
email: "hireme@dantydcook.com"            

# Optional social preview image (used if present)
social_image: "/assets/images/social-card.png"


permalink: pretty

markdown: kramdown
theme: minima

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  projects:
    output: true
    permalink: /projects/:name/
  essays:
    output: true
    permalink: /essays/:name/

# Plugins (works with Actions-based build)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-analytics
  - jekyll-sitemap

# Defaults for collections
defaults:
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: project
  - scope:
      path: "_essays"
      type: "essays"
    values:
      layout: essays
  # (optional) defaults for _pages content
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: default

# (Optional; not needed if using the 'pages' collection)
# include:
#   - _pages

analytics:
  provider: google-gtag
  gtag:
    tracking_id: G-51LKT0PS78
